name: "phpstan-ci:update-baseline"

on: workflow_dispatch

jobs:
  update_baseline:
    name: Update baseline files
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: latest
          tools: composer
          coverage: none

      - name: Composer install
        run: |
          composer install

      - name: Update Baselines
        run: php bin/update-baseline.php

      - name: Commit new files
        id: git-update
        run: |
          git config user.name ${GITHUB_ACTOR}
          git config user.email "${GITHUB_ACTOR}+github-actions@users.noreply.github.com"
          git add .
          git commit -m"phpstan-ci:update-baseline"
          git push origin ${GITHUB_REF_NAME}