name: "/update-phpstan-baseline"
on:
  issue_comment:
    types: [created, edited]
jobs:
  update_baseline:
    name: "Update Baseline files"
    if: contains(github.event.comment.html_url, '/pull/') && startsWith(github.event.comment.body, '/update-phpstan-baseline')
    runs-on: [ubuntu-latest]
    steps:
      - name: get upstream branch
        id: upstreambranch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "::set-output name=branchname::$(curl -H "Authorization: token ${GITHUB_TOKEN}" ${{ github.event.issue.pull_request.url }} | jq '.head.ref' | sed 's/\"//g')"

      - name: Checkout upstream repo
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.upstreambranch.outputs.branchname }}
            - id: ls
              run: ls

        - name: ls message
          uses: actions/github-script@0.9.0
          if: steps.ls.outputs.exitcode == 0
          env:
            STDOUT: "```${{ steps.ls.outputs.stdout }}```"
          with:
            github-token: ${{secrets.GITHUB_TOKEN}}
            script: |
              github.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: "#### `ls` Success\n" + process.env.STDOUT
              })